name: yodla_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  get:
  dio:
  retrofit:
  get_storage:
  sign_in_with_apple:
  camera:
  image_picker:
  web_socket_channel:
  audio_session:
  cached_network_image:
  lottie:
  intl:
  permission_handler:
  device_preview:
  google_fonts:
  country_flags: ^3.3.0
  mask_text_input_formatter: ^2.9.0
  dotted_line: ^3.2.3
  bottom_navy_bar: ^6.1.0
  rename: ^3.1.0
  svg_flutter:
  mobile_scanner:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  retrofit_generator:
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/
